### ISSUE TITLE
Errors when running Pogues-BO on tomcat v8.5.24 or Higher v8.5.xx

### ISSUE THREAD

**Issue by Badr-AKKA** [InseeFr/Pogues-Back-Office#81]
Pogues-BO works good on Tomcat v8.5.23 or older version, but it's not the case when i choose a newer version of Tomcat v8.5.xx

Bug: When running the projects i have this error 

`GRAVE: StandardWrapper.Throwable
java.lang.TypeNotPresentException: Type javax.persistence.PersistenceUnit not present 
at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
...
Caused by: java.lang.ClassNotFoundException: javax.persistence.PersistenceUnit 
at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1364)
...`

**Comment by bwerquin** [comment]
Dependancies to upgrade 
https://bz.apache.org/bugzilla/show_bug.cgi?id=61439#c2

**Comment by laurentC35** [comment]
Closed with use of spring boot
